title = "Dimitris Zorbas"
languageCode = "en-us"
PygmentsCodeFences = true
copyright = "All rights reserved - 2016"
theme = "hockus"
baseurl = "https://zorbash.com/"

[[menu.main]]
  name = "Github Repos"
  pre = "<h3>Follow me</h3>"
  url = "https://github.com/zorbash"
  weight = 100

[[menu.main]]
  name = "Twitter Timeline"
  url = "https://twitter.com/_zorbash"
  weight = 101

[[menu.main]]
  name = "Goodreads Profile"
  url = "https://www.goodreads.com/user/show/13437694-dimitrios"
  weight = 102

[[menu.main]]
  name = "SpeakerDeck Profile"
  url = "https://speakerdeck.com/zorbash"
  weight = 103

[params]
  description = "Code spells, smells and sourcery"
  hideHUGOSupport = true
  author = "Dimitris Zorbas"
  bio = "Brace sourcerer, engineer and open-source addict @ skroutz"
  authorwebsite = "https://zorbash.com"
  githubName = "zorbash"
  twitterName = "_zorbash"
  cover = "images/road.jpg"
  logo = "images/zorbash.jpg"
  googleAnalyticsUserId = "UA-89343761-1"

[params.social]
  twitter = "_zorbash"
